### ISSUE TITLE
Implement a function to calculate the model-implied covariance matrix

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Steiner/cSEM#15]
Please implement a function that calculates the model-implied covariance matrix. In doing so, we have to distinguish between a linear model, non-linear models, and CCA models. Currently, the latter allows composites to freely correlate.  

Implemenation progress:

- [x]  For linear factor models
- [x]  For linear composite models
- [ ]  For non-linear models
- [ ]  For CCA

**Comment by M-E-Steiner** [comment]
Implemenation progress:

- [ ] For linear model
- [ ] For non-linear models
- [ ] For CCA

**Comment by M-E-Steiner** [comment]
I will close this issue and move plans to implement a model implied covariance matrix for nonlinear models and CCA to the "long term plans" list in the cSEM project
