### ISSUE TITLE
Write function to test/check validity of selected results

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Steiner/cSEM#23]
We need a function that checks the results with repsect to the following:

- [x] -Is the model-implied correlation/covariance matrix of the indicators positive definite?
- [x] -Are absolute standardized factor loading estimates smaller than 1?
- [x] -Is the construct correlation matrix positive definite?
- [x] -Has any kind of algorithm thats been used, converged?

**Comment by M-E-Steiner** [comment]
Closes by #61
