### ISSUE TITLE
Return convergence status

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Steiner/cSEM#48]
If we use an iterative weighting scheme, we should return whether the alogrithm has converged. I would add a new element to the $Information list Convergence. If we use a weighting scheme where convergence is not relevant or if the algorithm has converged, we should write there TRUE otherwise FALSE. 

This argument can be used in the Status function to check whether the alogrithm has converged.

**Comment by M-E-Steiner** [comment]
Closed by #61
