### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by M-E-Steiner** [M-E-Steiner/cSEM#9]
The following tests need to be implemented:

- [ ] Overall test for model fit as proposed by Dijkstra and Henseler (2015)
- [ ] Hausman test

**Comment by FloSchuberth** [comment]
I have already an implementation of the bootstrap-based Hausman test. Please remind me to send it.

**Comment by M-E-Steiner** [comment]
Moved overall model fit to separate issue and Hausman test to the "long term plan" list in cSEM projects.
